[workspace]
resolver = "2"
version = "0.1.2"
members = [
  "contracts/mock-game-hub",
  "contracts/twenty-one",
  "contracts/number-guess",
  "contracts/dice-duel",
  "contracts/zkrps",
  "contracts/rps_game",
  "contracts/verifier",
]

[workspace.dependencies]
soroban-sdk = { git = "https://github.com/stellar/rs-soroban-sdk", rev = "e516750bd3e2d7624096b9681ad4174f6a7011a0" }

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[profile.release.package.ultrahonk_soroban_contract]
opt-level = 3

[profile.release.package.ultrahonk_soroban_verifier]
opt-level = 3

[profile.release.package.ark-ff]
opt-level = 3

[profile.release.package.ark-bn254]
opt-level = 3
